server:
  port: 80
spring:
  application:
    name: cloud-consumer-openfeign-order80

eureka:
  client:
    service-url:
      defaultZone: http://eureka.server7001.com:7001/eureka,http://eureka.server7002.com:7002/eureka